services:
  - type: web
    name: aicar-website
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SSL
        value: true

databases:
  - name: aicar-db
    plan: free
    databaseName: aicar_db

